const FIRST_USERS = 'FIRST_USERS';
const SEARCH_USERS = 'SEARCH_USERS';
const REMOVE_USERS = 'REMOVE_USERS';
const GET_USER = 'GET_USER';
const GET_REPOS = 'GET_REPOS';
const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';
const SET_LOADING = 'SET_LOADING';

export {
  FIRST_USERS,
  SEARCH_USERS,
  REMOVE_USERS,
  GET_USER,
  GET_REPOS,
  SET_ALERT,
  REMOVE_ALERT,
  SET_LOADING,
};
